### ISSUE TITLE
Incorrect  Comment Toggle Character

### ISSUE THREAD

**Issue by histamineblkr** [dkniffin/atom-nagios#1]
In atom when trying to "Toggle Comments" (Ctrl-/), it puts the Java style comment  `/*...*/`. When looking at the **~/.atom/packages/language-nagios/grammars/nagios-cfg.cson**, it appears the proper regexs are used for "#" and ";" to comment. 

I am unsure why atom defaults to the `/*...*/` style comments.

**Comment by dkniffin** [comment]
Closed via #2
